/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CadastrarRestauranteRouteImport } from './routes/cadastrar-restaurante'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestauranteSlugRouteImport } from './routes/restaurante.$slug'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRestauranteRoute = CadastrarRestauranteRouteImport.update({
  id: '/cadastrar-restaurante',
  path: '/cadastrar-restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteSlugRoute = RestauranteSlugRouteImport.update({
  id: '/restaurante/$slug',
  path: '/restaurante/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/cadastro': typeof CadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/restaurante/$slug': typeof RestauranteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/cadastro': typeof CadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/restaurante/$slug': typeof RestauranteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/cadastro': typeof CadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/restaurante/$slug': typeof RestauranteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/cadastrar-restaurante'
    | '/cadastro'
    | '/favoritos'
    | '/login'
    | '/painel'
    | '/restaurante/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastrar-restaurante'
    | '/cadastro'
    | '/favoritos'
    | '/login'
    | '/painel'
    | '/restaurante/$slug'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/cadastrar-restaurante'
    | '/cadastro'
    | '/favoritos'
    | '/login'
    | '/painel'
    | '/restaurante/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CadastrarRestauranteRoute: typeof CadastrarRestauranteRoute
  CadastroRoute: typeof CadastroRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  RestauranteSlugRoute: typeof RestauranteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-restaurante': {
      id: '/cadastrar-restaurante'
      path: '/cadastrar-restaurante'
      fullPath: '/cadastrar-restaurante'
      preLoaderRoute: typeof CadastrarRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante/$slug': {
      id: '/restaurante/$slug'
      path: '/restaurante/$slug'
      fullPath: '/restaurante/$slug'
      preLoaderRoute: typeof RestauranteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CadastrarRestauranteRoute: CadastrarRestauranteRoute,
  CadastroRoute: CadastroRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  RestauranteSlugRoute: RestauranteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
